# http://travis-ci.org/#!/MongoEngine/flask_mongoengine
language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - '3.4'
    - '3.5'
    - pypy
    - pypy3
env:
  - MONGOENGINE=0.7
  - MONGOENGINE=0.8
  - MONGOENGINE=0.9
  - MONGOENGINE=0.10.0
  - MONGOENGINE=dev
before_install:
- travis_retry sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
- echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' |
  sudo tee /etc/apt/sources.list.d/mongodb.list
- travis_retry sudo apt-get update
- travis_retry sudo apt-get autoremove
- travis_retry sudo apt-get autoclean
- travis_retry sudo apt-get install mongodb-org-server

install:
- travis_retry pip install tox>=1.9
- travis_retry tox -e $(echo py$TRAVIS_PYTHON_VERSION-me$MONGOENGINE | tr -d . | sed -e 's/pypypy/pypy/') -- -e test
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION-me$MONGOENGINE | tr -d . | sed -e 's/pypypy/pypy/') -- --with-coverage

notifications:
  irc: "irc.freenode.org#mongoengine"
branches:
  only:
    - master
    - dev
